Updating project to access Vaults
Every item is under a vault. Chaning project to only use vault as the
root of display.

Added goroutines to item retrieval for faster access time.

Cleaned up dmenu script for copying and removing from clipboard.

diff --git a/dmenu_oper b/dmenu_oper
--- a/dmenu_oper
+++ b/dmenu_oper
@@ -5,8 +5,7 @@ BASE64="base64"
 CLIP_TIME=45
 
 clip() {
-  read input
-	if [[ -n $WAYLAND_DISPLAY ]]; then
+	if [[ -n $WAYLAND_DISPLAY ]] && command -v wl-copy &> /dev/null; then
 		local copy_cmd=( wl-copy )
 		local paste_cmd=( wl-paste -n )
 		if [[ $X_SELECTION == primary ]]; then
@@ -14,12 +13,12 @@ clip() {
 			paste_cmd+=( --primary )
 		fi
 		local display_name="$WAYLAND_DISPLAY"
-	elif [[ -n $DISPLAY ]]; then
+	elif [[ -n $DISPLAY ]] && command -v xclip &> /dev/null; then
 		local copy_cmd=( xclip -selection "$X_SELECTION" )
 		local paste_cmd=( xclip -o -selection "$X_SELECTION" )
 		local display_name="$DISPLAY"
 	else
-		die "Error: No X11 or Wayland display detected"
+		die "Error: No X11 or Wayland display and clipper detected"
 	fi
 	local sleep_argv0="password store sleep on display $display_name"
 
@@ -28,11 +27,11 @@ clip() {
 	# trailing new lines.
 	pkill -f "^$sleep_argv0" 2>/dev/null && sleep 0.5
 	local before="$("${paste_cmd[@]}" 2>/dev/null | $BASE64)"
-	echo -n "$input" | "${copy_cmd[@]}" || die "Error: Could not copy data to the clipboard"
+	echo -n "$1" | "${copy_cmd[@]}" || die "Error: Could not copy data to the clipboard"
 	(
 		( exec -a "$sleep_argv0" bash <<<"trap 'kill %1' TERM; sleep '$CLIP_TIME' & wait" )
 		local now="$("${paste_cmd[@]}" | $BASE64)"
-		[[ $now != $(echo -n "$input" | $BASE64) ]] && before="$now"
+		[[ $now != $(echo -n "$1" | $BASE64) ]] && before="$now"
 
 		# It might be nice to programatically check to see if klipper exists,
 		# as well as checking for other common clipboard managers. But for now,
@@ -48,7 +47,8 @@ clip() {
 	echo "Copied $2 to clipboard. Will clear in $CLIP_TIME seconds."
 }
 
-password=$(./main list | dmenu -i -p "One Password:")
-if [ -n "$password" ]; then
-  ./main show "$password" | clip
+PASSNAME=$(./main list | dmenu -i -p "One Password:")
+if [ -n "$PASSNAME" ]; then
+  PASSWORD=$(./main show "$PASSNAME")
+  clip "$PASSWORD" "$PASSNAME"
 fi
